let qs=[];let currentUser=null;
const $=x=>document.getElementById(x);
async function api(u,o){const r=await fetch(u,o);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pretty(v){return String(v??'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
async function checkAdmin(){const d=await api('/api/admin/me');if(d.authenticated){currentUser=d.user;$('loginPanel').hidden=true;$('adminPanel').hidden=false;$('adminUser').textContent=`Signed in as ${d.user.email} · ${d.user.role==='admin'?'Administrator':'Content Editor'}`;document.querySelectorAll('.admin-only').forEach(x=>x.hidden=d.user.role!=='admin');await loadQuestions();showTab('questions')}else{$('loginPanel').hidden=false;$('adminPanel').hidden=true}}
async function login(e){e.preventDefault();$('loginMessage').textContent='';try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value})});$('loginForm').reset();await checkAdmin()}catch(e){$('loginMessage').textContent=e.message}}
async function logout(){await api('/api/admin/logout',{method:'POST'});await checkAdmin()}
async function loadQuestions(){qs=await api('/api/questions?limit=200&random=false&status=active');let ss=[...new Set(qs.map(q=>q.subject))].sort();$('subject').innerHTML='<option value="">All subjects</option>'+ss.map(s=>`<option>${esc(s)}</option>`).join('');render()}
function render(){let t=$('search').value.toLowerCase(),s=$('subject').value,d=$('difficulty').value,x=qs.filter(q=>(!s||q.subject===s)&&(!d||q.difficulty===d)&&(!t||`${q.question} ${q.subject} ${q.topic}`.toLowerCase().includes(t)));$('rows').innerHTML=x.map(q=>`<tr><td>${q.id}</td><td>${esc(q.subject)}</td><td>${esc(q.topic)}</td><td>${esc(q.difficulty)}</td><td>${esc(q.question)}</td><td><button onclick="edit(${q.id})">Edit</button> <button onclick="archive(${q.id})">Archive</button></td></tr>`).join('');$('status').textContent=`${x.length} questions shown`}
function openNew(){$('form').reset();$('id').value='';$('panel').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
async function edit(id){let q=await api('/api/questions/'+id);$('id').value=q.id;$('fs').value=q.subject;$('ft').value=q.topic;$('fd').value=q.difficulty;$('fq').value=q.question;$('a').value=q.options[0];$('b').value=q.options[1];$('c').value=q.options[2];$('d').value=q.options[3];$('correct').value=q.correct;$('ex').value=q.explanation;$('panel').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
async function archive(id){if(confirm('Archive this question? It will no longer appear in new assessments.')){await api('/api/questions/'+id,{method:'DELETE'});await loadQuestions()}}
async function loadResults(){const params=new URLSearchParams({search:$('resultSearch').value,status:$('resultStatus').value});const rows=await api('/api/admin/results?'+params);$('resultStatusMessage').textContent=`${rows.length} entries shown`;$('resultRows').innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.name)}</strong><br><span class="muted">${esc(r.email)}</span></td><td>${esc(r.subject)}</td><td><span class="status ${esc(r.status)}">${esc(pretty(r.status))}</span></td><td>${r.score===null?'—':`${r.score}/${r.total} (${r.percentage}%)`}</td><td>${esc(new Date(r.started_at).toLocaleString())}</td><td>${r.status==='completed'?`<button onclick="editResult(${r.id},${r.score},${r.total})">Edit Score</button> `:''}<button class="danger-btn" onclick="deleteResult(${r.id})">Delete</button></td></tr>`).join('')}
async function deleteResult(id){if(!confirm('Permanently delete this result from the database? This removes the attempt, its answers and its stored result. This cannot be undone.'))return;try{await api('/api/admin/results/'+id,{method:'DELETE'});await loadResults()}catch(e){alert(e.message)}}
async function editResult(id,score,total){const value=prompt(`Enter the new score (0-${total}):`,String(score));if(value===null)return;const next=Number(value);if(!Number.isInteger(next)||next<0||next>total){alert('Please enter a valid whole-number score.');return}try{await api('/api/admin/results/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({score:next})});await loadResults()}catch(e){alert(e.message)}}
async function loadUsers(){const params=new URLSearchParams({search:$('userSearch').value,role:$('userRole').value});const rows=await api('/api/admin/users?'+params);$('userRows').innerHTML=rows.map(u=>{const self=Number(u.id)===Number(currentUser.id);return `<tr><td><strong>${esc(u.name)}</strong><br><span class="muted">${esc(u.email)}</span></td><td>${self?'<span class="role-lock">Administrator · Environment managed</span>':`<select id="role-${u.id}"><option value="user" ${u.role==='user'?'selected':''}>User</option><option value="editor" ${u.role==='editor'?'selected':''}>Editor</option><option value="admin" ${u.role==='admin'?'selected':''}>Administrator</option></select>`}</td><td>${u.completed_attempts}/${u.attempts}</td><td>${esc(new Date(u.created_at).toLocaleDateString())}</td><td>${self?'<span class="muted">No actions</span>':`<button onclick="saveUser(${u.id})">Save Access</button>`}</td></tr>`}).join('')}
async function saveUser(id){const select=$('role-'+id);try{await api('/api/admin/users/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:select.value})});await loadUsers();await loadAudit()}catch(e){alert(e.message)}}
async function addUser(e){e.preventDefault();$('addUserMessage').textContent='';try{const d=await api('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('newUserName').value,email:$('newUserEmail').value,role:$('newUserRole').value,temporaryPassword:$('newUserPassword').value})});$('addUserForm').reset();$('newUserPassword').value='';$('addUserMessage').textContent=`User created. Temporary password: ${d.temporaryPassword}. Save it securely and give it to the user; it will not be shown again.`;await loadUsers();await loadAudit()}catch(e){$('addUserMessage').textContent=e.message}}
async function loadReports(){const rows=await api('/api/admin/reports?status='+encodeURIComponent($('reportStatus').value));$('reportStatusMessage').textContent=`${rows.length} reports shown`;$('reportRows').innerHTML=rows.map(r=>`<tr><td>${esc(r.name)}<br><span class="muted">${esc(r.email)}</span></td><td>${r.question_id?`#${r.question_id}`:'—'}<br>${esc(r.question)}</td><td>${esc(r.reason)}</td><td><span class="status ${esc(r.status)}">${esc(pretty(r.status))}</span></td><td>${esc(new Date(r.created_at).toLocaleString())}</td><td><select onchange="updateReport(${r.id},this.value)"><option value="open" ${r.status==='open'?'selected':''}>Open</option><option value="reviewed" ${r.status==='reviewed'?'selected':''}>Reviewed</option><option value="dismissed" ${r.status==='dismissed'?'selected':''}>Dismissed</option></select></td></tr>`).join('')}
async function updateReport(id,status){try{await api('/api/admin/reports/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await loadReports();await loadAudit()}catch(e){alert(e.message)}}
async function loadAudit(){const rows=await api('/api/admin/audit?search='+encodeURIComponent($('auditSearch').value));$('auditStatusMessage').textContent=`${rows.length} history entries shown`;$('auditRows').innerHTML=rows.map(r=>`<tr><td>${esc(new Date(r.created_at).toLocaleString())}</td><td><strong>${esc(r.actor_name)}</strong><br><span class="muted">${esc(r.actor_email)}</span></td><td>${esc(pretty(r.action))}</td><td>${esc(pretty(r.entity_type))}${r.entity_id?` #${r.entity_id}`:''}</td><td>${esc(Object.entries(r.details||{}).map(([k,v])=>`${pretty(k)}: ${typeof v==='object'?JSON.stringify(v):v}`).join(' · '))}</td></tr>`).join('')}
function showTab(name){document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=true);document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$(name+'Tab').hidden=false;if(name==='questions')loadQuestions();if(name==='results')loadResults();if(name==='users')loadUsers();if(name==='reports')loadReports();if(name==='audit')loadAudit()}
$('loginForm').onsubmit=login;$('logout').onclick=logout;$('addUserForm').onsubmit=addUser;$('form').onsubmit=async e=>{e.preventDefault();let id=$('id').value,x={subject:$('fs').value,topic:$('ft').value,difficulty:$('fd').value,question:$('fq').value,options:[$('a').value,$('b').value,$('c').value,$('d').value],correct:+$('correct').value,explanation:$('ex').value,status:'active'};try{await api(id?'/api/questions/'+id:'/api/questions',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});$('panel').hidden=true;await loadQuestions();if(currentUser.role==='admin')await loadAudit()}catch(e){alert(e.message)}};$('new').onclick=openNew;$('cancel').onclick=()=>$('panel').hidden=true;$('search').oninput=render;$('subject').onchange=render;$('difficulty').onchange=render;$('resultSearch').oninput=()=>loadResults();$('resultStatus').onchange=()=>loadResults();$('userSearch').oninput=()=>loadUsers();$('userRole').onchange=()=>loadUsers();$('reportStatus').onchange=()=>loadReports();$('auditSearch').oninput=()=>loadAudit();document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>showTab(t.dataset.tab)));checkAdmin().catch(e=>{$('loginMessage').textContent=e.message});
