let qs=[];const $=x=>document.getElementById(x);
async function api(u,o){const r=await fetch(u,o);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
async function checkAdmin(){const d=await api('/api/admin/me');if(d.authenticated){$('loginPanel').hidden=true;$('adminPanel').hidden=false;$('adminUser').textContent=`Signed in as ${d.user.email}`;await load()}else{$('loginPanel').hidden=false;$('adminPanel').hidden=true}}
async function login(e){e.preventDefault();$('loginMessage').textContent='';try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value})});$('loginForm').reset();await checkAdmin()}catch(e){$('loginMessage').textContent=e.message}}
async function logout(){await api('/api/admin/logout',{method:'POST'});await checkAdmin()}
async function load(){qs=await api('/api/questions?limit=100&random=false&status=active');let ss=[...new Set(qs.map(q=>q.subject))];$('subject').innerHTML='<option value="">All subjects</option>'+ss.map(s=>`<option>${esc(s)}</option>`).join('');render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){let t=$('search').value.toLowerCase(),s=$('subject').value,d=$('difficulty').value,x=qs.filter(q=>(!s||q.subject===s)&&(!d||q.difficulty===d)&&(!t||q.question.toLowerCase().includes(t)));$('rows').innerHTML=x.map(q=>`<tr><td>${q.id}</td><td>${esc(q.subject)}</td><td>${esc(q.topic)}</td><td>${esc(q.difficulty)}</td><td>${esc(q.question)}</td><td><button onclick="edit(${q.id})">Edit</button> <button onclick="archive(${q.id})">Archive</button></td></tr>`).join('');$('status').textContent=`${x.length} questions shown`}
function openNew(){$('form').reset();$('id').value='';$('panel').hidden=false}
async function edit(id){let q=await api('/api/questions/'+id);$('id').value=q.id;$('fs').value=q.subject;$('ft').value=q.topic;$('fd').value=q.difficulty;$('fq').value=q.question;$('a').value=q.options[0];$('b').value=q.options[1];$('c').value=q.options[2];$('d').value=q.options[3];$('correct').value=q.correct;$('ex').value=q.explanation;$('panel').hidden=false}
async function archive(id){if(confirm('Archive this question?')){await api('/api/questions/'+id,{method:'DELETE'});await load()}}
$('loginForm').onsubmit=login;$('logout').onclick=logout;$('form').onsubmit=async e=>{e.preventDefault();let id=$('id').value,x={subject:$('fs').value,topic:$('ft').value,difficulty:$('fd').value,question:$('fq').value,options:[$('a').value,$('b').value,$('c').value,$('d').value],correct:+$('correct').value,explanation:$('ex').value,status:'active'};try{await api(id?'/api/questions/'+id:'/api/questions',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});$('panel').hidden=true;await load()}catch(e){alert(e.message)}};$('new').onclick=openNew;$('cancel').onclick=()=>$('panel').hidden=true;$('search').oninput=render;$('subject').onchange=render;$('difficulty').onchange=render;checkAdmin().catch(e=>{$('loginMessage').textContent=e.message});
